project:
  type: book
  output-dir: docs
  
website:
  site-url: https://onelsoncarvalho.github.io/modelos_probabilidade/
  
book:
  title: "Modelos de Probabilidade"
  author: "Nelson Geraldo Aquino de Carvalho"
  date: "03/16/2024"
  chapters:
    - index.qmd
    - qui_quadrado.qmd
    - t_student.qmd
    - cauchy.qmd
    - lognormal.qmd
    - pareto_basica.qmd
    - pareto_generalizada.qmd
    - references.qmd
  page-footer:
    center: |
      Nelson Geraldo Aquino de Carvalho <br>
      https://onelsoncarvalho.github.io
      
bibliography: references.bib

format:
  html:
    theme: cosmo
    footer: "©2026 Nelson Geraldo Aquino de Carvalho — Modelos de Probabilidade"
