project:
  type: book
  output-dir: docs
  
book:
  title: "Modelos de Probabilidade"
  author: "Nelson Geraldo Aquino de Carvalho"
  date: "03/16/2024"
  chapters:
    - index.qmd
    # - summary.qmd
    - qui_quadrado.qmd
    - t_student.qmd
    - cauchy.qmd
    - lognormal.qmd
    - pareto_basica.qmd
    - pareto_generalizada.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
